const provincesList = {
    "15": "A Coruña",
    "03": "Alacant/Alicante",
    "02": "Albacete",
    "04": "Almería",
    "01": "Araba/Álava",
    "33": "Asturias",
    "05": "Ávila",
    "06": "Badajoz",
    "08": "Barcelona",
    "48": "Bizkaia",
    "09": "Burgos",
    "10": "Cáceres",
    "11": "Cádiz",
    "39": "Cantabria",
    "12": "Castelló/Castellón",
    "51": "Ceuta",
    "13": "Ciudad Real",
    "14": "Córdoba",
    "16": "Cuenca",
    "20": "Gipuzkoa",
    "17": "Girona",
    "18": "Granada",
    "19": "Guadalajara",
    "21": "Huelva",
    "22": "Huesca",
    "07": "Illes Balears",
    "23": "Jaén",
    "26": "La Rioja",
    "35": "Las Palmas",
    "24": "León",
    "25": "Lleida",
    "27": "Lugo",
    "28": "Madrid",
    "29": "Málaga",
    "52": "Melilla",
    "30": "Murcia",
    "31": "Navarra",
    "32": "Ourense",
    "34": "Palencia",
    "36": "Pontevedra",
    "37": "Salamanca",
    "38": "Santa Cruz de Tenerife",
    "40": "Segovia",
    "41": "Sevilla",
    "42": "Soria",
    "43": "Tarragona",
    "44": "Teruel",
    "45": "Toledo",
    "46": "València/Valencia",
    "47": "Valladolid",
    "49": "Zamora",
    "50": "Zaragoza"
};

export const convertCodeToProvinceName = (code) => {
    const provinceName = provincesList[code];
    return provinceName || null;
}

